### ISSUE TITLE
TS100

### ISSUE THREAD

**Issue by SwiftFlying** [Jan--Henrik/Otter-Iron#1]
Hi,
You designed a great PCB! I have some ideas to discuss with you.

Tom

**Comment by Jana-Marie** [comment]
Hey, Thanks! Sure, do you wan't to DM me or just write here? :)

**Comment by SwiftFlying** [comment]
Have you developed Otter-Iron firmware yet? https://www.tindie.com/products/LafrasH/modern-electronics-reflowr-v2/Are you interested in this Electronics ReflowR?If you are interested, I can finish the hardware part.And complete the prototype production.I'm in Shenzhen, China. It's very convenient to make prototypes.

**Comment by Jana-Marie** [comment]
I've not developed a usable firmware yet as I don't have any prototypes, but I've forked Clay's USB-PD firmware which will be the base of the Otter-Iron. https://github.com/Jan--Henrik/USB-PD-Firmware/tree/TS100C
It works and requests the power profile with the maximum power available.
I am not interested in the Electronics ReflowR, I have all the equipment I need at home, also I have ordered all parts for prototypes. If you want to build some prototypes for yourself, you can just do that, all parts of this project are open source.
