### ISSUE TITLE
jlcpcb SMT assembly not working

### ISSUE THREAD

**Issue by pecirep** [Jan--Henrik/Otter-Iron#11]
after uploading the newest v2.3 gerber files provided by you to JLCPCB.com the smt assembly option is greyed out and telling me that only certain boards (1.0-1.6mm thickness, green soldermask, etc. ) are allowed for assembly, all of which are correctly selected.
Re-exporting the gerbers did not help, although interestingly enough, the X2 gerber files do seem to work.
FWIW I was able to select SMT assembly for a different 4-layer board designed in KiCAD a few days ago, which makes this issue even more confusing to me.

Great work btw, hope to have this on the way soon! 👍

**Comment by Jana-Marie** [comment]
Hey, JLCSMT has a minimum board size requirement of 20* 20mm, the Otter-Iron is something like 10*89mm, thus it cannot be assembled by JLCSMT. To fix that I panelized two boards to fulfill the minimum size requirement, that are the x2 gerber files. 

Please use them, as well as the BOM and POS file in the same folder, for JLC SMT assembly. (note: I've not tested assembly of the TS100 yet, please double check for errors within the BOM and POS)
:)

**Comment by pecirep** [comment]
sorry, my bad, I completely missed this.
other than the components that jlc doesn't offer the bom and cpl files seem to be correct in the preview. Btw it turns out they do have the MCP9700AT-ETT, but under MCP9700AT-E/TT so that was only recognized with the slash.

Since I already made a fool of myself, there's a few more things that I'd like to ask:
Can the original display from the TS100 be reused?
Do you expect 100W (20V 5A) USB PD chargers to work and/or be safe?
Is there a reason you decided not to reuse both of the original tip holders?

**Comment by Jana-Marie** [comment]
> Btw it turns out they do have the MCP9700AT-ETT, but under MCP9700AT-E/TT so that was only recognized with the slash.
Ah nice, I will fix that BOM entry 

> Can the original display from the TS100 be reused?
Yes, but be careful when desoldering, the flatflex pcb breaks easily

> Do you expect 100W (20V 5A) USB PD chargers to work and/or be safe?
It does work and is safe, due to the tips resistance the maximum power drawn is ~50W

>  Is there a reason you decided not to reuse both of the original tip holders?
I strongly recommend to reuse them, the main problem is, that you cannot buy them directly from aliexpress. If you don't have a spare TS100 to salvage them, drop mini-ware an email and ask for them as replacement. Pricing is ~1$/set. The littlefuse-fuseholders listed in the BOM may damage the tip

**Comment by Aurical** [comment]
Appreciate you adding in the panelized version, but JLCSMD's [faq](https://support.jlcpcb.com/article/83-smt-assembly-faqs) claims that V-cut panelization is not supported, and panelization should use stamp holes. 

I am not too familiar with pcb design, but it looks like the panelized version is using v cuts, just wanted to check in with you on this.

**Comment by Jana-Marie** [comment]
No, it is using so called "mouse-bites". That is supported.

**Comment by pecirep** [comment]
> > Is there a reason you decided not to reuse both of the original tip holders?
> I strongly recommend to reuse them, the main problem is, that you cannot buy them directly from aliexpress. If you don't have a spare TS100 to salvage them, drop mini-ware an email and ask for them as replacement. Pricing is ~1$/set. The littlefuse-fuseholders listed in the BOM may damage the tip

on the newest version there's 2 small holes for the rear holder, instad of a center hole like in the front and on the original. how do I reuse the original one there? Just solder it down?

**Comment by Jana-Marie** [comment]
yes, the first holder can be screwed down (if the PCB is ordered with a thickness of 1-1.2mm) and the rear one has to be soldered down
