### ISSUE TITLE
Add footprints for original tip-holders

### ISSUE THREAD

**Issue by Jana-Marie** [Jan--Henrik/Otter-Iron#14]
Add footprints for the original tip-holders so that they don't have to be soldered on.

**Comment by Lo5t** [comment]
is there a reason why a fuse holder cannot be considered? 
something like this https://lcsc.com/product-detail/Fuse-Holders_Xucheng-Elec-C3130_C3130.html
is compatible with the hole for the back one but aligned the wrong way.

**Comment by Jana-Marie** [comment]
Please see: https://github.com/Jan--Henrik/Otter-Iron#tip-holders--mechanical-parts
