### ISSUE TITLE
Accelerometer planned?

### ISSUE THREAD

**Issue by zebaschdian** [Jan--Henrik/Otter-Iron#15]
First of all Great Project! I really love what you´re doing here. This is exactly what I´ve been searching for!
But on the original TS100 there is an accelerometer built in to put the device to sleep and wake it up again with the motion data. I really like this feature. So my question is, if it´s planned to implement this feature in the Otter-Iron?

Anyway I´m trying to rebuild the current PCB design and would like to give some support on the firmware.

**Comment by Jana-Marie** [comment]
Thanks! I do not plan to add a accelerometer, in fact I never used that feature. If one wants a standby function anyways my approach would be to check how much power is consumed and estimate usage/standby from that. This method saves costs and should work similarly good as the acc approach.

Sounds great, I should write down a list of planned features and bugs at some point :) If you need any help in rebuilding the Otter-Iron please contact me!
