### ISSUE TITLE
Minor layout issue with tagconnect header

### ISSUE THREAD

**Issue by kliment** [Jan--Henrik/Otter-Iron#4]
Hey, this is not a major concern but you might want to fix it anyway - the tagconnect spec says everything between the centers of the pads is a keepout zone - you have a trace and a groundplane in that area. Seems the trace can easily be routed around along the board edge and the groundplane doesn't need to extend there.

**Comment by Jana-Marie** [comment]
Hey, thanks for the input! I will add that to the list of hardware to-dos for the next revision. :)
