### ISSUE TITLE
Not an issue, but a question!

### ISSUE THREAD

**Issue by Mosher23** [Jan--Henrik/Otter-Iron#9]
Can it be used to accept Weller RT tips by just changing the hot tip socket?

thank you

**Comment by Jana-Marie** [comment]
Hey, It can be modified so it uses Weller RT tips, however you would need to split up the heater and thermocouple connection. To test this I made a small breakout board/devkit, my current goal is to add JBC tips to the TS100/Otter-Iron (Weller RT tips are quite similar) https://github.com/Jan--Henrik/Otter-Iron/tree/master/KiCAD/Otter-Iron_Devkit

**Comment by Mosher23** [comment]
Thank you so much for your reply
